backend:
  name: git-gateway
  branch: main 

media_folder: "Styles/Images" 
public_folder: "../../Styles/Images" 

editor:
  preview: false

collections:
  - name: "gallery_data"
    label: "Datos de la Galería"
    editor:
      preview: false
    files:
      - label: "Galería de Aves"
        name: "galeria"
        file: "Modules/Gallery/galeria.json"
        format: "json"
        extension: "json"
        fields:
          - label: "Aves"
            name: "aves"
            widget: "list"
            add_to_top: true
            collapsed: true
            summary: '{{fields.title}}'
            fields:
              - {label: "Imagen", name: "src", widget: "image"}
              - {label: "Título", name: "title", widget: "string"}
